//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courier
    {
        public Courier()
        {
            this.Tran = new HashSet<Tran>();
        }
    
        public int CourierID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        public string CourierName { get; set; }
        public string CourierDescription { get; set; }
        public string CourierAddress { get; set; }
        public string CourierTelephone { get; set; }
        public string AccountNumberUSD { get; set; }
        public string AccountNumberEUR { get; set; }
        public string AccountNumberEGP { get; set; }
    
        public virtual ICollection<Tran> Tran { get; set; }
    }
}
