//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.FeesInDischargePortNet = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortNet1 = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortNet2 = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortNet3 = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortNet4 = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortNet5 = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortNet6 = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortNet7 = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortNet8 = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortSelling = new HashSet<FeesInDischargePortSelling>();
            this.FeesInDischargePortSelling1 = new HashSet<FeesInDischargePortSelling>();
            this.FeesInDischargePortSelling2 = new HashSet<FeesInDischargePortSelling>();
            this.FeesInDischargePortSelling3 = new HashSet<FeesInDischargePortSelling>();
            this.FeesInDischargePortSelling4 = new HashSet<FeesInDischargePortSelling>();
            this.FeesInDischargePortSelling5 = new HashSet<FeesInDischargePortSelling>();
            this.FeesInDischargePortSelling6 = new HashSet<FeesInDischargePortSelling>();
            this.FeesInDischargePortSelling7 = new HashSet<FeesInDischargePortSelling>();
            this.FeesInDischargePortSelling8 = new HashSet<FeesInDischargePortSelling>();
            this.FeesInOriginNet = new HashSet<FeesInOriginNet>();
            this.FeesInOriginNet1 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginNet2 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginNet3 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginNet4 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginNet5 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginNet6 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginNet7 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginNet8 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginNet9 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginSelling = new HashSet<FeesInOriginSelling>();
            this.FeesInOriginSelling1 = new HashSet<FeesInOriginSelling>();
            this.FeesInOriginSelling2 = new HashSet<FeesInOriginSelling>();
            this.FeesInOriginSelling3 = new HashSet<FeesInOriginSelling>();
            this.FeesInOriginSelling4 = new HashSet<FeesInOriginSelling>();
            this.FeesInOriginSelling5 = new HashSet<FeesInOriginSelling>();
            this.FeesInOriginSelling6 = new HashSet<FeesInOriginSelling>();
            this.FeesInOriginSelling7 = new HashSet<FeesInOriginSelling>();
            this.FeesInOriginSelling8 = new HashSet<FeesInOriginSelling>();
            this.FeesInOriginSelling9 = new HashSet<FeesInOriginSelling>();
            this.TranDetail = new HashSet<TranDetail>();
            this.TranTotals = new HashSet<TranTotals>();
            this.TranProfit = new HashSet<TranProfit>();
            this.Config = new HashSet<Config>();
            this.FeesInDischargePortNet11 = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortNet21 = new HashSet<FeesInDischargePortNet>();
            this.FeesInDischargePortSelling11 = new HashSet<FeesInDischargePortSelling>();
            this.FeesInDischargePortSelling21 = new HashSet<FeesInDischargePortSelling>();
            this.FeesInOriginNet31 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginNet41 = new HashSet<FeesInOriginNet>();
            this.FeesInOriginSelling31 = new HashSet<FeesInOriginSelling>();
            this.FeesInOriginSelling41 = new HashSet<FeesInOriginSelling>();
            this.TranCharges = new HashSet<TranCharges>();
            this.TranCharges1 = new HashSet<TranCharges>();
            this.TranCharges2 = new HashSet<TranCharges>();
            this.TranCharges3 = new HashSet<TranCharges>();
            this.TranCharges4 = new HashSet<TranCharges>();
            this.TranContainer = new HashSet<TranContainer>();
            this.TranContainer1 = new HashSet<TranContainer>();
        }
    
        public int CurrencyID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
    
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet { get; set; }
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet1 { get; set; }
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet2 { get; set; }
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet3 { get; set; }
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet4 { get; set; }
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet5 { get; set; }
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet6 { get; set; }
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet7 { get; set; }
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet8 { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling1 { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling2 { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling3 { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling4 { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling5 { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling6 { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling7 { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling8 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet1 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet2 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet3 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet4 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet5 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet6 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet7 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet8 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet9 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling1 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling2 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling3 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling4 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling5 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling6 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling7 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling8 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling9 { get; set; }
        public virtual ICollection<TranDetail> TranDetail { get; set; }
        public virtual ICollection<TranTotals> TranTotals { get; set; }
        public virtual ICollection<TranProfit> TranProfit { get; set; }
        public virtual ICollection<Config> Config { get; set; }
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet11 { get; set; }
        public virtual ICollection<FeesInDischargePortNet> FeesInDischargePortNet21 { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling11 { get; set; }
        public virtual ICollection<FeesInDischargePortSelling> FeesInDischargePortSelling21 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet31 { get; set; }
        public virtual ICollection<FeesInOriginNet> FeesInOriginNet41 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling31 { get; set; }
        public virtual ICollection<FeesInOriginSelling> FeesInOriginSelling41 { get; set; }
        public virtual ICollection<TranCharges> TranCharges { get; set; }
        public virtual ICollection<TranCharges> TranCharges1 { get; set; }
        public virtual ICollection<TranCharges> TranCharges2 { get; set; }
        public virtual ICollection<TranCharges> TranCharges3 { get; set; }
        public virtual ICollection<TranCharges> TranCharges4 { get; set; }
        public virtual ICollection<TranContainer> TranContainer { get; set; }
        public virtual ICollection<TranContainer> TranContainer1 { get; set; }
    }
}
