//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeesInDischargePortSelling
    {
        public int TranID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        public string CustomsPersonName { get; set; }
        public Nullable<decimal> THC { get; set; }
        public Nullable<int> THCCurrencyID { get; set; }
        public Nullable<decimal> Truck { get; set; }
        public Nullable<int> TruckCurrencyID { get; set; }
        public Nullable<decimal> Pacing { get; set; }
        public Nullable<int> PacingCurrencyID { get; set; }
        public Nullable<decimal> License { get; set; }
        public Nullable<int> LicenseCurrencyID { get; set; }
        public Nullable<decimal> Recept { get; set; }
        public Nullable<int> ReceptCurrencyID { get; set; }
        public Nullable<decimal> Customs { get; set; }
        public Nullable<int> CustomsCurrencyID { get; set; }
        public Nullable<decimal> Clearance { get; set; }
        public Nullable<int> ClearanceCurrencyID { get; set; }
        public Nullable<decimal> OtherCustomsFees { get; set; }
        public Nullable<int> OtherCustomsFeesCurrencyID { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<int> OthersCurrencyID { get; set; }
        public Nullable<decimal> AdditionalField1 { get; set; }
        public Nullable<int> AdditionalField1CurrencyID { get; set; }
        public Nullable<decimal> AdditionalField2 { get; set; }
        public Nullable<int> AdditionalField2CurrencyID { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Currency Currency2 { get; set; }
        public virtual Currency Currency3 { get; set; }
        public virtual Currency Currency4 { get; set; }
        public virtual Currency Currency5 { get; set; }
        public virtual Currency Currency6 { get; set; }
        public virtual Currency Currency7 { get; set; }
        public virtual Currency Currency8 { get; set; }
        public virtual Currency Currency11 { get; set; }
        public virtual Currency Currency21 { get; set; }
        public virtual Tran Tran { get; set; }
    }
}
