//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMan
    {
        public SalesMan()
        {
            this.Tran = new HashSet<Tran>();
        }
    
        public int SalesManID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        public string SalesManName { get; set; }
        public string SalesManPhone { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Tran> Tran { get; set; }
    }
}
