//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingType
    {
        public ShippingType()
        {
            this.TranContainer = new HashSet<TranContainer>();
        }
    
        public int ShippingTypeID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        public string ShippingTypeName { get; set; }
        public int ShippingModeID { get; set; }
        public string Description { get; set; }
    
        public virtual ShippingMode ShippingMode { get; set; }
        public virtual ICollection<TranContainer> TranContainer { get; set; }
    }
}
