//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran
    {
        public Tran()
        {
            this.TranContainer = new HashSet<TranContainer>();
            this.TranProfit = new HashSet<TranProfit>();
            this.TranTotals = new HashSet<TranTotals>();
        }
    
        public int TranID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        public string TranRefNumber { get; set; }
        public string BLNo { get; set; }
        public Nullable<int> POL { get; set; }
        public Nullable<int> POD { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<int> CourierID { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> SalesManID { get; set; }
        public Nullable<int> CommodityID { get; set; }
        public int ShippingTermID { get; set; }
        public int OriginCountryID { get; set; }
        public Nullable<int> TT { get; set; }
        public string FinalDistination { get; set; }
        public string Notes { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Commodity Commodity { get; set; }
        public virtual Country Country { get; set; }
        public virtual Courier Courier { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual FeesInDischargePortNet FeesInDischargePortNet { get; set; }
        public virtual FeesInDischargePortSelling FeesInDischargePortSelling { get; set; }
        public virtual FeesInOriginNet FeesInOriginNet { get; set; }
        public virtual FeesInOriginSelling FeesInOriginSelling { get; set; }
        public virtual Port Port { get; set; }
        public virtual Port Port1 { get; set; }
        public virtual SalesMan SalesMan { get; set; }
        public virtual ShippingTerm ShippingTerm { get; set; }
        public virtual TranCharges TranCharges { get; set; }
        public virtual ICollection<TranContainer> TranContainer { get; set; }
        public virtual TranDetail TranDetail { get; set; }
        public virtual ICollection<TranProfit> TranProfit { get; set; }
        public virtual ICollection<TranTotals> TranTotals { get; set; }
    }
}
