//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranContainer
    {
        public int TranContainerID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        public int TranID { get; set; }
        public int ShippingTypeID { get; set; }
        public int Count { get; set; }
        public Nullable<decimal> LineShippingCharge { get; set; }
        public Nullable<int> LineShippingChargeCurrencyID { get; set; }
        public Nullable<decimal> LineShippingChargeSelling { get; set; }
        public Nullable<int> LineShippingChargeSellingCurrencyID { get; set; }
        public Nullable<decimal> LineShippingChargeTotal { get; set; }
        public Nullable<decimal> LineShippingChargeSellingTotal { get; set; }
    
        public virtual ShippingType ShippingType { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Tran Tran { get; set; }
    }
}
