//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranDetail
    {
        public int TranID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        public Nullable<int> DemurrageFreeDays { get; set; }
        public Nullable<int> DemurrageOverDays { get; set; }
        public Nullable<decimal> DemurrageCost { get; set; }
        public Nullable<int> DemurrageCostCurrencyID { get; set; }
        public Nullable<System.DateTime> CollectDate { get; set; }
        public string RemainingAmountNotes { get; set; }
        public bool PaymentFinished { get; set; }
        public string AdditionalField1Label { get; set; }
        public string AdditionalField2Label { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual TranStatus TranStatus { get; set; }
        public virtual Tran Tran { get; set; }
    }
}
