//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranProfit
    {
        public int ProfitID { get; set; }
        public int TranID { get; set; }
        public int CurrencyID { get; set; }
        public decimal TotalPaid { get; set; }
        public decimal TotalEarned { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Tran Tran { get; set; }
    }
}
