//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(AgentMetadata))]
    public partial class Agent
    {
    }

    public partial class AgentMetadata
    {
    
        public int AgentID { get; set; }

        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }

         [System.ComponentModel.DisplayName("Agent Name")]
        public string AgentName { get; set; }
        public int CountryID { get; set; }

         [System.ComponentModel.DisplayName("Phone Number")]
        public string PhoneNumber { get; set; }
        public string Notes { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Tran> Tran { get; set; }
    }
}
