//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;



    [MetadataType(typeof(AspNetUsersMetadata))]
    public partial class AspNetUsers
    {
    }

    public partial class AspNetUsersMetadata
    {
    
        public string Id { get; set; }

         [System.ComponentModel.DisplayName("User Name")]
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }

         [System.ComponentModel.DisplayName("Description")]
        public string Discriminator { get; set; }
          [System.ComponentModel.DisplayName("Administrator ?")]
        public bool IsAdministrator { get; set; }

          [System.ComponentModel.DisplayName("Accounting ?")]
        public bool IsAccounting { get; set; }

          [System.ComponentModel.DisplayName("Operation ?")]
        public bool IsOperation { get; set; }

          [System.ComponentModel.DisplayName("Sales ?")]
        public bool IsSales { get; set; }

          [System.ComponentModel.DisplayName("Customer Service ?")]
        public bool IsCustomerService { get; set; }

          [System.ComponentModel.DisplayName("Custom Clearance ?")]
          public bool IsCustomClearance { get; set; }

         [System.ComponentModel.DisplayName("Can Login ?")]
        public bool CanLogin { get; set; }
    
        //public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }
        //public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }
        //public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}
