//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    [MetadataType(typeof(ConfigMEtaData))]
    public partial class Config
    {
    }

    public partial class ConfigMEtaData
    {
        public int ConfigID { get; set; }

        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }

        [System.ComponentModel.DisplayName("Administrator Password")]
        public string SystemPassword { get; set; }

        [System.ComponentModel.DisplayName("Default Currrency for the system")]
        public int DefaultCurrency { get; set; }
    }
}
