//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;


    using System.ComponentModel.DataAnnotations;


    [MetadataType(typeof(CountryMetaData))]
    public partial class Country
    {
    }

    public partial class CountryMetaData
    {
    
        public int CountryID { get; set; }

        public System.DateTime Updated { get; set; }
        public string Updator { get; set; }
        [System.ComponentModel.DisplayName("Country Name")]
        public string CountryName { get; set; }
    
        public virtual ICollection<Agent> Agent { get; set; }
        public virtual ICollection<Tran> Tran { get; set; }
        public virtual ICollection<Port> Port { get; set; }
    }
}
