//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    [MetadataType(typeof(CourierMetaData))]
    public partial class Courier
    {
    }

    public partial class CourierMetaData
    {    
        public int CourierID { get; set; }

        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }

        [System.ComponentModel.DisplayName("Courier Name")]
        public string CourierName { get; set; }

        [System.ComponentModel.DisplayName("Description")]
        public string CourierDescription { get; set; }
        [System.ComponentModel.DisplayName("Courier Address")]
        public string CourierAddress { get; set; }

        [System.ComponentModel.DisplayName("Courier Phone")]
        public string CourierTelephone { get; set; }

        [System.ComponentModel.DisplayName("Account Number (USD)")]
        public string AccountNumberUSD { get; set; }

        [System.ComponentModel.DisplayName("Account Number (EUR)")]
        public string AccountNumberEUR { get; set; }

        [System.ComponentModel.DisplayName("Account Number (EGP)")]
        public string AccountNumberEGP { get; set; }
    }
}
