//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;


    [MetadataType(typeof(CustomerMetaData))]
    public partial class Customer
    {
    }

    public partial class CustomerMetaData
    {
    
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        
        [System.ComponentModel.DisplayName("Customer Name")]

        public string CustomerName { get; set; }

        [System.ComponentModel.DisplayName("Phone Number")]
        public string PhoneNumber1 { get; set; }
        [System.ComponentModel.DisplayName("Mobile Number")]
        public string PhoneNumber2 { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Tran> Tran { get; set; }
        public virtual ICollection<Tran> Tran1 { get; set; }
    }
}
