//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MeasurementMetaData))]
    public partial class Measurement
    {
    }
    public partial class MeasurementMetaData
    {
    
        public int MeaurementID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        [System.ComponentModel.DisplayName("Measurement Name")]
        public string MeasurementName { get; set; }

        [System.ComponentModel.DisplayName("Description")]
        public string MeasurementDescription { get; set; }
    
        public virtual ICollection<ShippingMode> ShippingMode { get; set; }
    }
}
