//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(ShippingTermMetaData))]
    public partial class ShippingTerm
    {
    }
    public partial class ShippingTermMetaData
    {
    
        public int ShippingTermID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        [System.ComponentModel.DisplayName("Shipping Term Name")]
        public string ShippingTermName { get; set; }
        [System.ComponentModel.DisplayName("Description")]
        public string ShippingTermDescription { get; set; }
    
        public virtual ICollection<Tran> Tran { get; set; }
    }
}
