//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(ShippingModeMetaData))]
    public partial class ShippingMode
    {
    }
    public partial class ShippingModeMetaData
    {
          
        public int ShippingModeID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        [System.ComponentModel.DisplayName("Shipping Mode Name")]
        public string ShippingModeName { get; set; }
        public int MeasurementID { get; set; }
        public string Description { get; set; }
    
        //public virtual Measurement Measurement { get; set; }
        //public virtual ICollection<ShippingType> ShippingType { get; set; }
    }
}
