//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(ShippingTypeMetaData))]
    public partial class ShippingType
    {
    }
    public partial class ShippingTypeMetaData
    {
        public int ShippingTypeID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }
        [System.ComponentModel.DisplayName("Shipping Type Name")]
        public string ShippingTypeName { get; set; }
        public int ShippingModeID { get; set; }
        public string Description { get; set; }

        public virtual ShippingMode ShippingMode { get; set; }
    }
}
