//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(TranProfitMetaData))]
    public partial class TranProfit
    {
    }
    public partial class TranProfitMetaData
    {
        
        public int ProfitID { get; set; }
        public int TranID { get; set; }
        public int CurrencyID { get; set; }
        [System.ComponentModel.DisplayName("Total Paid")]
        public decimal TotalPaid { get; set; }
        [System.ComponentModel.DisplayName("Total Earned")]
        public decimal TotalEarned { get; set; }
        [System.ComponentModel.DisplayName("Total Profit")]
        public Nullable<decimal> Profit { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Tran Tran { get; set; }
    }
}
