//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(TranTotalsMetaData))]
    public partial class TranTotals
    {
    }
    public partial class TranTotalsMetaData
    {
        public int TranID { get; set; }
        public string FinType { get; set; }
        public int CurrencyID { get; set; }
        public decimal FinTotal { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Tran Tran { get; set; }
    }
}
