//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(TranChargesMetaData))]
    public partial class TranCharges
    {
    }
    public partial class TranChargesMetaData
    {
        public int TranID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Updator { get; set; }

        // [System.ComponentModel.DisplayName("Line Shipping Charge")]
        //public Nullable<decimal> LineShippingCharge { get; set; }
        //public Nullable<int> LineShippingChargeCurrencyID { get; set; }
        // [System.ComponentModel.DisplayName("Line Shipping Charge Total ")]
        //public Nullable<decimal> LineShippingChargeTotal { get; set; }

        //[System.ComponentModel.DisplayName("Line Shipping Charge Selling ")]
        //public Nullable<decimal> LineShippingChargeSelling { get; set; }
        //public Nullable<int> LineShippingChargeSellingCurrencyID { get; set; }
        // [System.ComponentModel.DisplayName("Line Shipping Charge Selling Total")]
        //public Nullable<decimal> LineShippingChargeSellingTotal { get; set; }

         [System.ComponentModel.DisplayName("Commission Percentage")]
         public Nullable<decimal> CommissionPercentage { get; set; }
         [System.ComponentModel.DisplayName("Paid Commission")]
        public Nullable<decimal> PaidCommission { get; set; }
        public Nullable<int> PaidCommissionCurrencyID { get; set; }
         [System.ComponentModel.DisplayName("Bank Percentage")]
        public Nullable<decimal> BankPercentage { get; set; }
         [System.ComponentModel.DisplayName("Bank Transfer Fees")]
        public Nullable<decimal> BankTransferFees { get; set; }
        public Nullable<int> BankTransferFeesCurrencyID { get; set; }

        [System.ComponentModel.DisplayName("Others Fees")]
        public Nullable<decimal> OtherFees { get; set; }
        public Nullable<int> OtherFeesCurrencyID { get; set; }
    
        //public virtual Currency Currency { get; set; }
        //public virtual Currency Currency1 { get; set; }
        //public virtual Currency Currency2 { get; set; }
        //public virtual Currency Currency3 { get; set; }
        //public virtual Currency Currency4 { get; set; }
        //public virtual Tran Tran { get; set; }
    }
}
